function draw() {
    // create some nodes
    var nodes = [
        { id: 100, label: "Open", group: 1, size: 100, fixed: true, shape: "circle" },
        { id: 1, label: "Open Data", group: 1 },
        { id: 2, label: "Open Access", group: 1 },
        { id: 3, label: "Open Standards", group: 1 },
        { id: 4, label: "Open Innovation", group: 1 },
        { id: 5, label: "Open Science", group: 1 },
        { id: 6, label: "Open Culture", group: 1 },
        { id: 7, label: "Open Education", group: 1 },
        { id: 8, label: "Open Government", group: 1 },
        { id: 9, label: "Open Business", group: 1 },
        { id: 10, label: "Open Society", group: 2 },
        { id: 11, label: "Open Technology", group: 2 },
        { id: 12, label: "Open Content", group: 3 },
        { id: 13, label: "Open Infrastructure", group: 2 },
        { id: 14, label: "Open Knowledge", group: 2 },
        { id: 15, label: "Open Software", group: 2 },
        { id: 16, label: "Open Standards", group: 3 },
        { id: 17, label: "Open Collaboration", group: 3 },
        { id: 18, label: "Open Design", group: 3 },
        { id: 19, label: "Open Platforms", group: 3 },
        { id: 20, label: "Open Hardware", group: 3 },
        { id: 21, label: "Open Web", group: 3 },
        { id: 22, label: "Open Data", group: 3 },
        { id: 23, label: "Open Licensing", group: 3 },
        { id: 24, label: "Open API", group: 4 },
        { id: 25, label: "Open Communications", group: 4 },
        { id: 26, label: "Open Format", group: 5 },
        { id: 27, label: "Open Geospatial", group: 4 },
        { id: 28, label: "Open Mindset", group: 0 },
        { id: 29, label: "Open Network", group: 2 },
        { id: 30, label: "Open Product", group: 3 },
        { id: 31, label: "Open Source Software", group: 2 },
        { id: 32, label: "Open Community", group: 2 },
        { id: 33, label: "Open Minds", group: 2 },
        { id: 34, label: "Open Knowledge Management", group: 2 },
        { id: 35, label: "Open Innovation Management", group: 2 },
        { id: 36, label: "Open Business Models", group: 2 },
        { id: 37, label: "Open Collaboration Platforms", group: 2 },
        { id: 38, label: "Open Value Networks", group: 2 },
        { id: 39, label: "Open Digital Transformation", group: 4 },
        { id: 40, label: "Open Solutions", group: 6 },
        { id: 41, label: "Open Services", group: 4 },
        { id: 42, label: "Open Business Ecosystems", group: 4 },
        { id: 43, label: "Open Collaborative Economy", group: 5 },
        { id: 44, label: "Open Leadership", group: 5 },
        { id: 45, label: "Open Supply Chains", group: 5 },
        { id: 46, label: "Open Innovation Networks", group: 5 },
        { id: 47, label: "Open Human Resources", group: 5 },
        { id: 48, label: "Open Talent Management", group: 5 },
        { id: 49, label: "Open Talent Development", group: 5 },
        { id: 50, label: "Open Diversity & Inclusion", group: 5 },
        { id: 51, label: "Open Talent Acquisition", group: 5 },
        { id: 52, label: "Open Workforce Development", group: 5 },
        { id: 53, label: "Open Learning & Development", group: 5 },
        { id: 54, label: "Open Organizational Culture", group: 5 },
        { id: 55, label: "Open Organizational Structure", group: 5 },
        { id: 56, label: "Open Organizational Design", group: 5 },
        { id: 57, label: "Open Organizational Development", group: 5 },
        { id: 58, label: "Open Organizational Transformation", group: 5 },
        { id: 59, label: "Open Decision Making", group: 5 },
        { id: 60, label: "Open Decision Support", group: 5 },
        { id: 61, label: "Open Decision Science", group: 5 },
        { id: 62, label: "Open Business Processes", group: 4 },
        { id: 63, label: "Open Business Strategies", group: 4 },
        { id: 64, label: "Open Work Practices", group: 4 },
        { id: 65, label: "Open Employee Engagement", group: 4 },
        { id: 66, label: "Open Talent Management", group: 4 },
        { id: 67, label: "Open Organizational Design", group: 4 },
        { id: 68, label: "Open Leadership", group: 4 },
        { id: 69, label: "Open Decision Making", group: 4 },
        { id: 70, label: "Open Communication Channels", group: 4 },
        { id: 71, label: "Open Customer Relationships", group: 4 },
        { id: 72, label: "Open Customer Feedback", group: 4 },
        { id: 73, label: "Open Customer Experience", group: 4 },
        { id: 74, label: "Open Customer Insights", group: 4 },
        { id: 75, label: "Open Customer Engagement", group: 4 }
    ];
    // add central node
    // var nodes = [].concat(nodes);

    // // create some edges
    // var edges = [
    //     { from: 1, to: 0 },
    //     { from: 2, to: 0 },
    //     { from: 3, to: 0 },
    //     { from: 3, to: 2 },
    //     { from: 4, to: 0 },
    //     { from: 5, to: 0 },
    //     { from: 6, to: 0 },
    //     { from: 7, to: 0 },
    //     { from: 8, to: 0 },
    //     { from: 9, to: 0 },
    //     { from: 11, to: 10 },
    //     { from: 11, to: 3 },
    //     { from: 11, to: 2 },
    //     { from: 11, to: 0 },
    //     { from: 12, to: 11 },
    //     { from: 13, to: 11 },
    //     { from: 14, to: 11 },
    //     { from: 15, to: 11 },
    //     { from: 17, to: 16 },
    //     { from: 18, to: 16 },
    //     { from: 18, to: 17 },
    //     { from: 19, to: 16 },
    //     { from: 19, to: 17 },
    //     { from: 19, to: 18 },
    //     { from: 20, to: 16 },
    //     { from: 20, to: 17 },
    //     { from: 20, to: 18 },
    //     { from: 20, to: 19 },
    //     { from: 21, to: 16 },
    //     { from: 21, to: 17 },
    //     { from: 21, to: 18 },
    //     { from: 21, to: 19 },
    //     { from: 21, to: 20 },
    //     { from: 22, to: 16 },
    //     { from: 22, to: 17 },
    //     { from: 22, to: 18 },
    //     { from: 22, to: 19 },
    //     { from: 22, to: 20 },
    //     { from: 22, to: 21 },
    //     { from: 23, to: 16 },
    //     { from: 23, to: 17 },
    //     { from: 23, to: 18 },
    //     { from: 23, to: 19 },
    //     { from: 23, to: 20 },
    //     { from: 23, to: 21 },
    //     { from: 23, to: 22 },
    //     { from: 23, to: 12 },
    //     { from: 23, to: 11 },
    //     { from: 24, to: 23 },
    //     { from: 24, to: 11 },
    //     { from: 25, to: 24 },
    //     { from: 25, to: 23 },
    //     { from: 25, to: 11 },
    //     { from: 26, to: 24 },
    //     { from: 26, to: 11 },
    //     { from: 26, to: 16 },
    //     { from: 26, to: 25 },
    //     { from: 27, to: 11 },
    //     { from: 27, to: 23 },
    //     { from: 27, to: 25 },
    //     { from: 27, to: 24 },
    //     { from: 27, to: 26 },
    //     { from: 28, to: 11 },
    //     { from: 28, to: 27 },
    //     { from: 29, to: 23 },
    //     { from: 29, to: 27 },
    //     { from: 29, to: 11 },
    //     { from: 30, to: 23 },
    //     { from: 31, to: 30 },
    //     { from: 31, to: 11 },
    //     { from: 31, to: 23 },
    //     { from: 31, to: 27 },
    //     { from: 32, to: 11 },
    //     { from: 33, to: 11 },
    //     { from: 33, to: 27 },
    //     { from: 34, to: 11 },
    //     { from: 34, to: 29 },
    //     { from: 35, to: 11 },
    //     { from: 35, to: 34 },
    //     { from: 35, to: 29 },
    //     { from: 36, to: 34 },
    //     { from: 36, to: 35 },
    //     { from: 36, to: 11 },
    //     { from: 36, to: 29 },
    //     { from: 37, to: 34 },
    //     { from: 37, to: 35 },
    //     { from: 37, to: 36 },
    //     { from: 37, to: 11 },
    //     { from: 37, to: 29 },
    //     { from: 38, to: 34 },
    //     { from: 38, to: 35 },
    //     { from: 38, to: 36 },
    //     { from: 38, to: 37 },
    //     { from: 38, to: 11 },
    //     { from: 38, to: 29 },
    //     { from: 39, to: 25 },
    //     { from: 40, to: 25 },
    //     { from: 41, to: 24 },
    //     { from: 41, to: 25 },
    //     { from: 42, to: 41 },
    //     { from: 42, to: 25 },
    //     { from: 42, to: 24 },
    //     { from: 43, to: 11 },
    //     { from: 43, to: 26 },
    //     { from: 43, to: 27 },
    //     { from: 44, to: 28 },
    //     { from: 44, to: 11 },
    //     { from: 45, to: 28 },
    //     { from: 47, to: 46 },
    //     { from: 48, to: 47 },
    //     { from: 48, to: 25 },
    //     { from: 48, to: 27 },
    //     { from: 48, to: 11 },
    //     { from: 49, to: 26 },
    //     { from: 49, to: 11 },
    //     { from: 50, to: 49 },
    //     { from: 50, to: 24 },
    //     { from: 51, to: 49 },
    //     { from: 51, to: 26 },
    //     { from: 51, to: 11 },
    //     { from: 52, to: 51 },
    //     { from: 52, to: 39 },
    //     { from: 53, to: 51 },
    //     { from: 54, to: 51 },
    //     { from: 54, to: 49 },
    //     { from: 54, to: 26 },
    //     { from: 55, to: 51 },
    //     { from: 55, to: 49 },
    //     { from: 55, to: 39 },
    //     { from: 55, to: 54 },
    //     { from: 55, to: 26 },
    //     { from: 55, to: 11 },
    //     { from: 55, to: 16 },
    //     { from: 55, to: 25 },
    //     { from: 55, to: 41 },
    //     { from: 55, to: 48 },
    //     { from: 56, to: 49 },
    //     { from: 56, to: 55 },
    //     { from: 57, to: 55 },
    //     { from: 57, to: 41 },
    //     { from: 57, to: 48 },
    //     { from: 58, to: 55 },
    //     { from: 58, to: 48 },
    //     { from: 58, to: 27 },
    //     { from: 58, to: 57 },
    //     { from: 58, to: 11 },
    //     { from: 59, to: 58 },
    //     { from: 59, to: 55 },
    //     { from: 59, to: 48 },
    //     { from: 59, to: 57 },
    //     { from: 60, to: 48 },
    //     { from: 60, to: 58 },
    //     { from: 60, to: 59 },
    //     { from: 61, to: 48 },
    //     { from: 61, to: 58 },
    //     { from: 61, to: 60 },
    //     { from: 61, to: 59 },
    //     { from: 61, to: 57 },
    //     { from: 61, to: 55 },
    //     { from: 62, to: 55 },
    //     { from: 62, to: 58 },
    //     { from: 62, to: 59 },
    //     { from: 62, to: 48 },
    //     { from: 62, to: 57 },
    //     { from: 62, to: 41 },
    //     { from: 62, to: 61 },
    //     { from: 62, to: 60 },
    //     { from: 63, to: 59 },
    //     { from: 63, to: 48 },
    //     { from: 63, to: 62 },
    //     { from: 63, to: 57 },
    //     { from: 63, to: 58 },
    //     { from: 63, to: 61 },
    //     { from: 63, to: 60 },
    //     { from: 63, to: 55 },
    //     { from: 64, to: 55 },
    //     { from: 64, to: 62 },
    //     { from: 64, to: 48 },
    //     { from: 64, to: 63 },
    //     { from: 64, to: 58 },
    //     { from: 64, to: 61 },
    //     { from: 64, to: 60 },
    //     { from: 64, to: 59 },
    //     { from: 64, to: 57 },
    //     { from: 64, to: 11 },
    //     { from: 65, to: 63 },
    //     { from: 65, to: 64 },
    //     { from: 65, to: 48 },
    //     { from: 65, to: 62 },
    //     { from: 65, to: 58 },
    //     { from: 65, to: 61 },
    //     { from: 65, to: 60 },
    //     { from: 65, to: 59 },
    //     { from: 65, to: 57 },
    //     { from: 65, to: 55 },
    //     { from: 66, to: 64 },
    //     { from: 66, to: 58 },
    //     { from: 66, to: 59 },
    //     { from: 66, to: 62 },
    //     { from: 66, to: 65 },
    //     { from: 66, to: 48 },
    //     { from: 66, to: 63 },
    //     { from: 66, to: 61 },
    //     { from: 66, to: 60 },
    //     { from: 67, to: 57 },
    //     { from: 68, to: 25 },
    //     { from: 68, to: 11 },
    //     { from: 68, to: 24 },
    //     { from: 68, to: 27 },
    //     { from: 68, to: 48 },
    //     { from: 68, to: 41 },
    //     { from: 69, to: 25 },
    //     { from: 69, to: 68 },
    //     { from: 69, to: 11 },
    //     { from: 69, to: 24 },
    //     { from: 69, to: 27 },
    //     { from: 69, to: 48 },
    //     { from: 69, to: 41 },
    //     { from: 70, to: 25 },
    //     { from: 70, to: 69 },
    //     { from: 70, to: 68 },
    //     { from: 70, to: 11 },
    //     { from: 70, to: 24 },
    //     { from: 70, to: 27 },
    //     { from: 70, to: 41 },
    //     { from: 70, to: 58 },
    //     { from: 71, to: 27 },
    //     { from: 71, to: 69 },
    //     { from: 71, to: 68 },
    //     { from: 71, to: 70 },
    //     { from: 71, to: 11 },
    //     { from: 71, to: 48 },
    //     { from: 71, to: 41 },
    //     { from: 71, to: 25 },
    //     { from: 72, to: 26 },
    //     { from: 72, to: 27 },
    //     { from: 72, to: 11 },
    //     { from: 73, to: 48 },
    //     { from: 74, to: 48 },
    //     { from: 74, to: 73 },
    //     { from: 75, to: 69 },
    //     { from: 75, to: 68 },
    //     { from: 75, to: 25 },
    //     { from: 75, to: 48 },
    //     { from: 75, to: 41 },
    //     { from: 75, to: 70 },
    //     { from: 75, to: 71 },
    //     { from: 76, to: 64 },
    //     { from: 76, to: 65 },
    //     { from: 76, to: 66 },
    //     { from: 76, to: 63 },
    //     { from: 76, to: 62 },
    //     { from: 76, to: 48 },
    //     { from: 76, to: 58 },
    // ];

    // update connections (edges) to point to central node
    var edges = nodes.map(function (node, index) {
        return { from: node.id, to: 100 };
    });
    // var edges = [];
    // for (var i = 0; i < nodes.length; i++) {
    //     var fromNode = nodes[i];
    //     var randomNumber = Math.random();
    //     if (randomNumber < 0.5) {
    //         var toNode = nodes[Math.floor(Math.random() * nodes.length)];
    //         edges.push({ from: fromNode.id, to: toNode.id });
    //     }
    // }

    // create a network
    var container = document.getElementById("mynetwork");
    container.style.clientWidth = '100%';
    container.style.clientHeight = '100%';
    var data = {
        nodes: nodes,
        edges: edges,
    };
    // nodes[100].size = 62;
    var options = {
        // width: "100%",
        // height: "100%",
        autoResize: true,
        nodes: {
            shape: "dot",
            size: 42,
            font: {
                size: 42,
                color: '#000000'
            }
        },
        physics: {
            forceAtlas2Based: {
                gravitationalConstant: -26,
                centralGravity: 0.005,
                springLength: 1600,
                springConstant: 0.18,
            },
            maxVelocity: 146,
            solver: "forceAtlas2Based",
            timestep: 0.35,
            stabilization: { iterations: 150 },
        },
    };
    var network = new vis.Network(container, data, options);
}

window.addEventListener("load", () => {
    draw();
});
